### ISSUE TITLE
Bug(localization): TranslocoLocaleService currency error

### ISSUE THREAD

**Issue by medvidekPanda** [jsverse/transloco#627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Locale

### Is this a regression?

Yes

### Current behavior

Number locallization in controller returns this error

Cannot read properties of undefined (reading 'currency') at TranslocoLocaleService.localizeNumber (ngneat-transloco-locale.mjs:849:36)

translocoLocaleService.localizeNumber(1000, 'currency') // $1,000.00

Decimal and percent works OK.
Pipe in template with currency works OK too.

### Expected behavior

Number localize with translocoLocaleService.localizeNumber(1000, 'currency') works in controller.

### Please provide a link to a minimal reproduction of the bug

-

### Please provide the environment you discovered this bug in

```markdown
Transloco: 4.2.2
Angular: 14.x
Node: v16.16.0
Package Manager: npm 8.11.0
OS: macOS
```

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
Please provide a reproduction link.

**Comment by Mikosko** [comment]
Hello, I don't have reproduction link but I guess that guy above did something like this.

`import { Pipe, PipeTransform } from "@angular/core";
import { TranslocoLocaleService } from "@ngneat/transloco-locale";

@Pipe({
  name: "agCustom",
  pure: false,
  standalone: true
})
export class CustomPipe implements PipeTransform {
  constructor(public translocoLocaleService: TranslocoLocaleService) {}

  transform(value: any, ...args: any[]) {
    this.translocoLocaleService.localizeNumber(1, "currency");

    return value;
  }
}
`

When you use this example pipe in template it's fail on same error.

**Comment by shaharkazaz** [comment]
Take a look at the [source code](https://github.com/ngneat/transloco/blob/master/libs/transloco-locale/src/lib/transloco-locale.service.ts#L135), when you pass currency you must provide options as well, global or by passing them as argument.

**Comment by shaharkazaz** [comment]
Feel free to reopen with reproduction.
