### ISSUE TITLE
Bug(migrate): No files match pattern during migration

### ISSUE THREAD

**Issue by hakimio** [jsverse/transloco#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

transloco

### Is this a regression?

Yes

### Current behavior

Trying to migrate a project from `ngx-translate`, I get `No files match the pattern` for all file patterns even the files exist in the specified path.
```
Migrating HTML files 📜
√ Step 1/2: Migrating directives
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*.html
√ Step 2/2: Migrating pipes
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*.html
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*.html

Migrating TS files 📜
√ Step 1/5: Migrating modules
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*.ts
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*.ts
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*.ts
√ Step 2/5: Migrating service imports
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*.ts
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*.ts
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*.ts
√ Step 3/5: Migrating constructor injections
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*.ts
√ Step 4/5: Migrating service usage
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*.ts
√ Step 5/5: Migrating specs
⚠️ No files match the pattern: C:\Users\PC1\SomePath\MyApp\src\app\**\*spec.ts
```

### Expected behavior

Migration should successfully migrate the files.

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/s/ngneat-transloco-kn52hs

### Please provide the environment you discovered this bug in

```markdown
Transloco: 5.0.7
Angular: 16
Node: 18
Package Manager: yarn v1
OS: Windows 10
```

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
@hakimio which transloco version is this? 5 is too general 🙂

**Comment by hakimio** [comment]
Might be `replace-in-file` latest version issue: https://github.com/adamreisnz/replace-in-file/issues/165

**Comment by hakimio** [comment]
Latest, `5.0.7`.

**Comment by hakimio** [comment]
Ok, I can confirm that it works correctly with `replace-in-file` `v6.3.5`, but not with the latest `v7.0.1`.
So it's an issue with `replace-in-file` library.

**Comment by shaharkazaz** [comment]
@hakimio I think you are correct, Let's downgrade to the latest v6, can you test and open a PR? I don't have a win machine

**Comment by hakimio** [comment]
@shaharkazaz the person who reported [the issue](https://github.com/adamreisnz/replace-in-file/issues/165) in `replace-in-file` repo fixed it by [changing path match patterns](https://github.com/windingwind/zotero-plugin-template/pull/63/files#diff-d3831cd61824ee8713cea7361c0fe4cb921f80deb8eaec5ebccc434be0e96d6eL133). 
So, I'm not sure if it would be best to downgrade the library or try to change all the patterns on `transloco` side.

**Comment by shaharkazaz** [comment]
@hakimio this needs to be tested on both machines.
Can you explain why this was resolved by replacing the `path.join` usage?

**Comment by hakimio** [comment]
I only know what the bug reporter wrote.
In the bug report he wrote:
```
We replaced RplaceInFileOption.files with the correct glob pattern and it works fine, however in 6.3.5, \\**\*.js also works fine, which is confusing.
```

In the PR, where he replaced `path.join`, he wrote the following in Chinese (rough google translation):
```
ReplaceInFileConfig.files should be a list of glob patterns, \\ is not recognized unless windowsPathsNoEscape is enabled.

replace-in-file 6.3.5 works fine confusingly, don't understand why it works, but still by glob requirement.
```

And `replace-in-file` [maintainer doesn't have Windows PC either](https://github.com/adamreisnz/replace-in-file/issues/165#issuecomment-1602547197)...

**Comment by shaharkazaz** [comment]
@hakimio Ok, so it feels like that `replace-in-file` should pass `windowsPathsNoEscape` to glob under the hood, I actually did this change in Transloco's schematics a couple of weeks ago.

**Comment by hakimio** [comment]
Do you want to open PR in `replace-in-file` repo?

**Comment by shaharkazaz** [comment]
@hakimio I think that's the better solution here, but IDK when the maintainer might be back so no ETA on the fix.

**Comment by hakimio** [comment]
Ok, for now I can just pin `replace-in-file` version on my end:
```json
"resolutions": {
    "replace-in-file": "6.3.5"
  }
```

**Comment by shaharkazaz** [comment]
@hakimio I think the migration script is the only one using it, so once done you shouldn't encounter it anymore

**Comment by hakimio** [comment]
@shaharkazaz are you going to create a PR in `replace-in-file` or should I do it?

**Comment by hakimio** [comment]
PR: https://github.com/adamreisnz/replace-in-file/pull/169

**Comment by saeidi-dev** [comment]
Has this issue been reviewed, and are you currently working on it?

**Comment by hakimio** [comment]
This still needs to be fixed on the transloco side. Glob options need to be updated.

**Comment by shaharkazaz** [comment]
@hakimio We just need to provide the glob configuration on Transloco's end? want to open a PR for it?

**Comment by hakimio** [comment]
@shaharkazaz PR: #797

**Comment by shaharkazaz** [comment]
@hakimio @saeidi-dev Can you please verify v7.4.4?

**Comment by saeidi-dev** [comment]
Yes, I tested it on version 7.4.4 and it worked properly.
