### ISSUE TITLE
Feature(testing): Testing feature libraries in a nx monorepo

### ISSUE THREAD

**Issue by mackelito** [jsverse/transloco#720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Transloco, Scoped Libs

### Is your feature request related to a problem? Please describe

When writing unit tests there is always console.warn about missing translations but they are not missing.

### Describe the solution you'd like

Documentations on a dynamic DRY approach on how to test standalone components that reside in a structure outside the app.
example:
apps
 - app1
 - app2
libs
 - feature1
 - feature2

i18n translations are in the features folder

### Describe alternatives you've considered

```markdown
N/A
```

### I would like to make a pull request for this feature

No

**Comment by shaharkazaz** [comment]
Feel free to reopen with reproduction/test repo.
