### ISSUE TITLE
Chore: 🤖 upgrade to angular v17

### ISSUE THREAD

**Issue by whernebrink** [jsverse/transloco#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Don't know / other

### Describe the solution you'd like

Transloco to support Angular 17. Nx is already supporting, if that would matter.

### I would like to make a pull request for this feature

No

**Comment by whernebrink** [comment]
@NetanelBasal How should this be done? Is it just an nx migration that needs to be ran? I could try helping out, but would be great with some pointers. We really would like to migrate and try angular 17 for our application and transloco is the only thing that is preventing us right now. :)

**Comment by beloveddd** [comment]
I have the same issue with Transloco and Angular 17 :(

**Comment by alexdabast** [comment]
I just created a brand new angular 17 app installed @ngneat/transloco and it works fine 
So what's the issue

**Comment by hernebrink** [comment]
@shaharkazaz, thanks for getting back to this. Indeed it works! Not sure why we experienced an issue with our upgrade. I've tested with 6.0.1 and it works. Thanks. :)

**Comment by shaharkazaz** [comment]
@whernebrink can you share what was the issue you faced?

**Comment by alexdabast** [comment]
I don't know then if my PR is still required @shaharkazaz. I guess it would be nice to have the repo updated to the latest version. I have push all the changes that you asked for the PR btw

**Comment by theguidingstar** [comment]
I am getting this error after migration to Angular 17 @alexdabast 
Anything I'm doing wrong here??

```
node_modules/@ngneat/transloco/lib/transloco.providers.d.ts:23:21 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@angular/core")' call instead.

23     provide: import("@angular/core").InjectionToken<Content>;
                       ~~~~~~~~~~~~~~~

node_modules/@ngneat/transloco/lib/transloco.service.d.ts:1:27 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@angular/core")' call instead.

1 import { OnDestroy } from '@angular/core';
                            ~~~~~~~~~~~~~~~

node_modules/@ngneat/transloco/lib/transloco.service.d.ts:10:21 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@angular/core")' call instead.

10 import * as i0 from "@angular/core";
```

**Comment by shaharkazaz** [comment]
@theguidingstar Make sure you are using the latest `@jsverse/transloco`. There is no known issue as the latest transloco versions support Angular 16+
