### ISSUE TITLE
Proper changelogs...

### ISSUE THREAD

**Issue by mackelito** [jsverse/transloco#749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) will this feature affect?

Transloco

### Is your feature request related to a problem? Please describe

When updating It's hard to get a overview of what has changed.
a proper changelog would be really nice

### Describe the solution you'd like

Something like https://github.com/jsverse/transloco-keys-manager/blob/master/CHANGELOG.md

### Describe alternatives you've considered

```markdown
N/A
```

### I would like to make a pull request for this feature

No

**Comment by shaharkazaz** [comment]
@mackelito Each lib has it's own changelog
<img width="711" alt="image" src="https://github.com/jsverse/transloco/assets/17194830/2fce0d50-0db1-449d-a931-194282b75085">

**Comment by mackelito** [comment]
Ah.. sorry.. I was expecting it to be the changelog in root.. thx! :) 😊
