### ISSUE TITLE
Can't add Transloco to a project:  collection.json does not exist

### ISSUE THREAD

**Issue by benfante** [jsverse/transloco#759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Schematics

### Is this a regression?

Yes

### Current behavior

When i try to add Transloco to an Angular (17) project, I receive the following error:

```bash
$ ng add @jsverse/transloco
ℹ Using package manager: npm
✔ Found compatible package version: @jsverse/transloco@7.2.0.
✔ Package information loaded.

The package @jsverse/transloco@7.2.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Path "<omitted>/node_modules/@jsverse/transloco/schematics/src/collection.json" does not exist.
```

### Expected behavior

I expect the add schematic should be run.

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/p/devbox/github/codesandbox/sandbox-templates/tree/main/angular

### Please provide the environment you discovered this bug in

```markdown
Transloco: 7.2.0
Angular: 17.3.0
Node: v20.11.1
Package Manager: npm (10.4.0)
OS: Linux Mint 21.2
```

### Browser

```markdown
Not relevant...
```

### I would like to make a pull request for this bug

No

**Comment by gkTim** [comment]
Also get this error seems schematics are not part of the npm package, but also there is no extra package.
Is it not ready yet or is this an error?

**Comment by timeoutguy** [comment]
Downgrade to 7.1.0 worked for me. thx @gkTim

**Comment by shaharkazaz** [comment]
I guess there was something wrong with the build, I'll bump and release a new version 👍

**Comment by shaharkazaz** [comment]
@benfante @gkTim @timeoutguy It should be ok in v7.2.1, can you verify?

**Comment by lkuendig** [comment]
> @benfante @gkTim @timeoutguy It should be ok in v7.2.1, can you verify?

I verified, it works. thank you!

**Comment by benfante** [comment]
I verified too. It works. Thanks.

**Comment by gkTim** [comment]
> @benfante @gkTim @timeoutguy It should be ok in v7.2.1, can you verify?

Thanks for the quick fix and the awesome work!
