### ISSUE TITLE
Unused imports detected (when marking comments for extraction)

### ISSUE THREAD

**Issue by MikeDabrowski** [jsverse/transloco#771]
First of all I am actually not sure how to label this issue, even where to place it. 

The key-extractor says to put `import {} from '@jsverse/transloco` if you want the comments extracted. The IDE has a tool to remove unused imports, which the mentioned one counts as. So on commit/keyboard shortcut the import gets removed and you may not notice.

To prevent that (and still have auto remove unused imports) we were just importing the whole module like `import @jsverse/transloco`. That worked fine for years. 

Now the Angular ships with esbuild or application builder. Tons of various errors and warnings. One of which is `ignored-bare-import`.

![image](https://github.com/jsverse/transloco/assets/17836911/f995b6e4-b9ea-490c-9c9d-2066dbbaf174)

They argue not to expose esbuilder config options. On the other hand esbuilder does not support config file (I was hoping it would act as some kind of a middleman). So currently there is no way to override this warning.

I am not an expert here - just reading the warning - maybe setting sideEffects to true would be enough? Merely importing the package actually has a side effect - key being extracted. Would that make sense?

**Comment by shaharkazaz** [comment]
@MikeDabrowski Hey! This one belongs in the keys manager lib.
I've [updated the docs](https://github.com/jsverse/transloco-keys-manager/commit/a75836b7b0b26e4a0d9503e9914a725a5338a97a) because adding the following comment also works: `// @jsverse/transloco`
Solves the issue right?

**Comment by shaharkazaz** [comment]
@MikeDabrowski I think I wanted the comments to be less verbose and more minimalistic, but this can be on top of the current behavior, and in the next major we can decide maybe to drop one. WDYT? would you like to open a PR for it?

**Comment by MikeDabrowski** [comment]
I agree. It doesn't have to be 'transloco(*)'  I just put it there as an example. Maybe simple `t` would work too but would have to restrict it to the comments - well it might turn out to be a pretty complex regex :D 

I can take care of it at some point. Maybe you could move this issue to the key-manager repo and assign it to me.

**Comment by shaharkazaz** [comment]
@MikeDabrowski When you have the change just open an issue/PR with the suggested solution, closing this for now 🙂
