### ISSUE TITLE
Bug(scope): Infitite loop caused by transpiler params algo rewrite

### ISSUE THREAD

**Issue by igorrust** [jsverse/transloco#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

Yes

### Current behavior

Running one of our projects causes an infitite loop in `transpile()`. Pre Transloco v7 this wasn't the case.

The use case is that we want to translate a value+unit duration object to a string. for example `{ seconds: 20 }` should be translated to `20s`. However, we also wanted the possibility to specify per language the order between value and unit, i.e. to have the same input resulting in `s20` (swapping the value and the unit), thus having this configurable via a translation-entry. The translation string we defined is `{ "COMPONENT_FORMAT": "{{value}}{{unit}}" }` for our default languages, but for another language we might define `{"COMPONENT_FORMAT": "{{unit}{{value}}"}`. As translation parameters we provide `value` and `unit` and in the resulting string we interpolate the actual values into.

When running the code, it hangs the application (in `transpile()`, I believe due to the introduced `while`-loop from this commit: https://github.com/jsverse/transloco/commit/8447634588210771047c45072186f20867fd8a2). I created a simple reproduction scenario, and the sandbox protects it from a hang:

![image](https://github.com/user-attachments/assets/2d3882fa-9eb3-428b-a4ea-6faaaa4757fe)

### Expected behavior

I would expect the `translate()` return the same result as before the Transloco upgrade, or a way to configure/avoid this situation.

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/p/sandbox/jsverse-transloco-forked-9lfrxp?file=%2Fsrc%2Fapp%2Finline-loaders%2Finline-loaders.component.ts  (I modified the **Inline Loaders** component, it should throw an error to the console).

### Transloco Config

```markdown
Everything provided in https://codesandbox.io/s/ngneat-transloco-kn52hs is sufficient to reproduce the issue
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 7.4.2
Angular: 17
Node: 18.18.2
Package Manager: NPM 9.8.1
OS: Win10
```

### Browser

```markdown
Firefox: 127.0.2 (64-bit)
```

### I would like to make a pull request for this bug

Yes 🚀

**Comment by shaharkazaz** [comment]
@igorrust Can you clarify why you are passing the following params:
```json
{"value": "{{ value }}", "unit": "{{ unit }}" }
```
These are bound to make an infinity loop.

**Comment by igorrust** [comment]
In the end I was able to solve it, by using a different interpolation-characters (`[[`, `]]`). Because originally I was translating `{{value}}{{unit}}` indeed with those parameters `{{value}}` and `{{unit}}` creating the loop (though this wasn't happening before in v6). but now I use `[[value]]` and `[[unit]]` as parameters to replace `{{value}}` with. And in the next step I replace with the actual values doing a `replaceAll([[ ${key} ]]` etc instead of `replaceAll({{ ${key} ]]`.

And thanks @shaharkazaz for replying so quickly!

**Comment by shaharkazaz** [comment]
@igorrust sure, no problem. 
I'm still not sure I followed exactly what your code flow is, but as long as you were able to resolve it I'm glad. 

Can you close this issue? No
