### ISSUE TITLE
Bug(persist-lang): Cookie storage with initialization in SSR can lead to inconsistency

### ISSUE THREAD

**Issue by musabhusaini** [jsverse/transloco#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Persist Lang

### Is this a regression?

No

### Current behavior

When using the `cookieStorage` method for persisting language with server-side rendering, the cookie is being set for the path that the page was rendered with. This means that language can change depending on which initial page was fetched from the server. To reproduce in the given [sandbox](https://codesandbox.io/p/devbox/admiring-bell-dvxqvt):

1. Click on nav link titled "Foo".
2. Refresh the page.
3. Click on "Toggle language".
4. Note that current language shows "es".
5. Click on nav link titled "Home".
6. Note that current language still shows "es".
7. Refresh the page.
8. Notice that current language is now "en".

### Expected behavior

Current language should be "es".

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/p/devbox/admiring-bell-dvxqvt

### Transloco Config

```markdown
Nothing special. Included in the sandbox.
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 7.4.3
Angular: 18.1.2
Node: 20.11.1
Package Manager: npm
OS: Windows/Linux
```

### Browser

```markdown
Edge version 126.0.2592.102 (Official build) (64-bit)
```

### Additional context

I believe this can be solved by setting the [cookie path](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_where_cookies_are_sent) to `/` when persisting the language in the cookie.

### I would like to make a pull request for this bug

Yes 🚀

**Comment by shaharkazaz** [comment]
@musabhusaini Nice 😀  should be an easy fix, would love to see a PR!

**Comment by musabhusaini** [comment]
> @musabhusaini Nice 😀 should be an easy fix, would love to see a PR!

@shaharkazaz: Sure, I would love to work on a PR. It might take some time as I have a few other things to wrap up! 😅

**Comment by shaharkazaz** [comment]
@musabhusaini This doesn't seem to happen anymore 🤔 Can you verify?

**Comment by musabhusaini** [comment]
> @musabhusaini This doesn't seem to happen anymore 🤔 I'll add the path explicitly just to be on the safe side

Thanks for the fix. It's working now.

Just to close the loop on this, I tried the old version, and the issue was still there, but the effect is slightly different than how I described it. To observe, you have to:

1. Open the [preview](https://dvxqvt-4200.csb.app/foo) in a new tab
2. Ensure your `translocoLang` cookie is not present.
3. Click on "Toggle Language".
4. Refresh the page and observe the "Current language" display.

You will notice that the value flickers, starting with `en` and then switching to `es`.

![transloco](https://github.com/user-attachments/assets/6538e730-f5e4-48ff-a0fe-f770f662d0ca)
