### ISSUE TITLE
Bug(scope): Synchronous Transloco not working

### ISSUE THREAD

**Issue by watchity** [jsverse/transloco#788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

Yes

### Current behavior

The html elements are not shown when I add the decorator *transloco="let t". Even if I put it on an ng-container or a div, it won't render the block that contains the decorator.
I've also tried injecting TranslocoService into component, and the html renders, but translate(key) returns an empty string.
But, if I call it with selectTranslate(key).subscribe() the translation is correct.

### Expected behavior

It should work with all methods.

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/s/jsverse-transloco-forked-ywgvfy?file=/src/app/app.component.html

### Transloco Config

```markdown
config: {
        availableLangs: ['en', 'es', 'ca'],
        defaultLang: 'en',
        fallbackLang: ['ca', 'es', 'en'],
        // Remove this option if your application doesn't support changing language in runtime.
        reRenderOnLangChange: true,
        prodMode: !isDevMode(),
      },
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 7.4.3
Angular: 18.1.0
Node: 18.20.3
Package Manager: pnpm
OS: Manjaro Linux x64
```

### Browser

```markdown
All
```

### Additional context

Angular CLI: 18.1.1
Node: 18.20.3
Package Manager: pnpm 9.6.0
OS: linux x64

Angular: 18.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.1
@angular-devkit/build-angular   18.1.1
@angular-devkit/core            18.1.1
@angular-devkit/schematics      18.1.1
@schematics/angular             18.1.1
rxjs                            7.8.1
typescript                      5.5.3
zone.js                         0.14.8

### I would like to make a pull request for this bug

Yes 🚀

**Comment by watchity** [comment]
Sorry, I'm not closing it in case it happens to someone else in the future, but it was simply that I was missing the Module import in my component, since it does not appear in the documentation and I had not taken it into account.

Just add TranslocoModule to the imports.

**Comment by shaharkazaz** [comment]
@watchity If you are using a standalone you can also import just what you need 🙂
