### ISSUE TITLE
`TranslocoHttpLoader` doesn't load the translation file

### ISSUE THREAD

**Issue by ahmedkhairydev** [jsverse/transloco#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

Yes

### Current behavior

`TranslocoHttpLoader` doesn't load the translation file without using `TranslocoPipe` inside the component.
I'm injecting the `TranslocoService` inside a custom `TitleService` to handle the browser tab title.

The current behavior is that the `TranslocoService` can't get the translation because the loader doesn't load it.

### Expected behavior

`TranslocoHttpLoader` should load the translation file even if I don't use the `TranslocoPipe`.
It should load the translation file at least when injecting the `TranslocoService`.

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/p/sandbox/transloco-loader-issue-t2hvyp

### Transloco Config

```markdown
provideHttpClient(),
provideTransloco({
  config: {
    availableLangs: ["en-US", "ar-JO"],
    defaultLang: "en-US",
    reRenderOnLangChange: true,
    prodMode: !isDevMode(),
  },
  loader: TranslocoHttpLoader,
}),
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 7.5.0
Angular: 18.2.9
Node: 20.12.2
Package Manager: npm
OS: Windows
```

### Browser

```markdown
Edge (latest)
```

### Additional context

you have to uncomment the code inside the `OnPush` Component and import the `TranslocoPipe`.

### I would like to make a pull request for this bug

No

**Comment by shaharkazaz** [comment]
Hey, this isn't a bug; this is how the library works. If you want to load the translations manually, you can use the load method on the Transloco service.

**Comment by ahmedkhairydev** [comment]
Great! Thanks for your help. I did it and it's working fine.
