### ISSUE TITLE
Bug(scope):  SyntaxError: Unexpected token 'export' after update from Angular 18 to 19

### ISSUE THREAD

**Issue by ChristianSchwarz** [jsverse/transloco#817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Relates to https://github.com/jsverse/transloco/issues/714 but non of the described fixes work

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

Yes

### Current behavior

after the update to Angular 19 the jest test don't compile anymore:

{code}

    C:\projects\xyz\src\Web\Client\node_modules\flat\index.js:10
    export function flatten(target, opts) {
    ^^^^^^

    SyntaxError: Unexpected token 'export'

    >  | import { translate } from '@jsverse/transloco';
       | ^
{code}

### Expected behavior

it should compile as with Angular 18

### Please provide the environment you discovered this bug in

```markdown
Transloco: "@jsverse/transloco": "^7.5.0",
Angular: 19
Node: v20.17.0
Package Manager: npm 10.8.2


"jest": "^29.7.0",
"jest-preset-angular": "^14.4.2",
"jest-transform-stub": "^2.0.0",


the jest.config.ts already contains the transformIgnorePatterns mentioned in https://github.com/jsverse/transloco/issues/714
transformIgnorePatterns: ['node_modules/?!(.*\\.mjs$|@jsverse)'],
```

### Additional context

Relates to https://github.com/jsverse/transloco/issues/714

**Comment by seventyeight** [comment]
We have added 
```
  transformIgnorePatterns: ['node_modules/?!(.\\*.mjs$|@jsverse)'],
  moduleNameMapper: {
    '^flat': 'node_modules/flat/index.js',
  },
```
in our `jest.preset.js`. Now it works.

**Comment by ChristianSchwarz** [comment]
@seventyeight if we use it like you describe we get:

```
   Configuration error:
    
    Could not locate module flat mapped as:
    node_modules/flat/index.js.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^flat/": "node_modules/flat/index.js"
      },
      "resolver": undefined
    }

       5 | import { cypressId } from '../../../../helpers/cypressId';
       6 | import { T } from 'T';
    >  7 | import { TranslocoPipe, translate } from '@jsverse/transloco';
         | ^
       8 |
       9 | @Component({
      10 |     selector: 'gcert-dialog-actions',

```
----

if we use `'^flat': '<rootDir>/node_modules/flat/index.js'` instead to make sure the correct dir is used we are back where we started:
```
export function flatten(target, opts) {
    ^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by shaharkazaz** [comment]
@ChristianSchwarz Hey, if you create a fresh repo does it reproduce? this is also required to provide a reproduction when submitting an issue

**Comment by lmullot** [comment]
To fix the issue I forced flat dependencies in `package.json`

```
  "overrides": {
    "@jsverse/transloco": {
      "flat": "5.0.2"
    },
  }
```

Then I removed the specific `transformIgnorePatterns` and `moduleNameMapper` for flat.

Hope that helps for quick fix

**Comment by guillerot** [comment]
for some reason, module name mapping doesn't work on `<rootDir>/node_modules/flat`
If I copy `<rootDir>/node_modules/flat/index.js` to my project, ie: `<rootDir>/overrides/flat/index.js`
I can map, and jest test will be back to normal
```ts
  "moduleNameMapper": {
    "^@lucca/cdk/(.*)$": "<rootDir>/projects/lucca-cdk/$1/src/public-api.ts",
    "^flat": "<rootDir>/overrides/flat/index.js"
  },
```

**Comment by ChristianSchwarz** [comment]
We fixed the issue by setting the "flat" version to "5.0.2" in the package.json, but we workaround https://github.com/jsverse/transloco/issues/817#issuecomment-2544854886 looks more clear.

@shaharkazaz  many people have the same problem and for some projects there is no clean solution yet. What about removing the dependency to "flat" from transloco? It seems like "flat" provides only a few utility functions that could be rewritten in transloco. This would save a lot of time for us users, see how many people had this issue and in #714 too. I assume that a total of +100 hours were wasted on the “flat” problem.
